In [1]:
import pandas as pd
from DomainLevel import Transformer
import os, math
from IPython.display import clear_output
import numpy as np

YREQ_ROOT_DIR='./stratosphere/req.y.csv/'
UNIQUE_YREQ_ROOT_DIR='./stratosphere/unique.req.y.csv/'

def get_filenames(__dir):
    ycsv_list = []
    for walker in os.walk(__dir):
        for filename in walker[2]:
            try:
                ycsv_list.append(filename)
            except pd.errors.EmptyDataError:
                print(f'File <{filename}> is empty.')
    return ycsv_list

/home/princio/anaconda3/envs/keras/lib/python3.8/site-packages/tldextract/.tld_set
/home/princio/anaconda3/envs/keras/lib/python3.8/site-packages/tldextract/.tld_set

In [47]:
ycsv_list = get_filenames(UNIQUE_YREQ_ROOT_DIR)
th = 0.5
df_DN_legit_nosfx = pd.DataFrame()
df_DN_legit_last = pd.DataFrame()
for n, filename in enumerate(ycsv_list):
    print(f'{n+1:5}/{len(ycsv_list)}: {filename}.')
    df = pd.read_csv(os.path.join(UNIQUE_YREQ_ROOT_DIR, filename))
    df_nosfx = df[(df['dsfx_legit'] == 0) & (df['nosfx'] < th)][['dsfx', 'counts']].groupby('dsfx').sum()
    df_last = df[(df['dsfx_legit'] == 0) & (df['last'] < th)][['dsfx', 'counts']].groupby('dsfx').sum()
    df_DN_legit_nosfx = pd.concat([df_DN_legit_nosfx, df_nosfx]).groupby('dsfx').sum()
    df_DN_legit_last = pd.concat([df_DN_legit_last, df_last]).groupby('dsfx').sum()
    clear_output()

In [45]:
df_DN_legit_nosfx.sort_values(by='counts', ascending=False).head(n=20)

                       counts
dsfx
anyplace-gateway.info  520335
messagingengine.com    336888
digitalwaves.co.nz     336796
pekasn.com             333725
vmfiti.com             333701
...                       ...
gruposerac.com.br           1
rag-bone.org                1
ragapriya.org               1
raggajam.ru                 1
kyoei-vn.com                1

[151610 rows x 1 columns]

In [49]:
df_DN_legit_last.sort_values(by='counts', ascending=False).head(n=20)

                         counts
dsfx
acn.name                 595703
anyplace-gateway.info    520335
alacartebelini.com       412818
messagingengine.com      336888
digitalwaves.co.nz       336796
pekasn.com               333725
vmfiti.com               333701
latehost.net             208869
method.in                198875
ghanashippingawards.com  137928
cvl.name                 126772
bibrath.eu               108724
beezsize.com             106906
joinparty4more.xyz        83150
wpad.lan                  76489
comecomefindme.ru         75784
site-serv.com             64367
mi2c.info                 59391
dyndns.org                26601
psmtp.com                 24904