In [1]:
from Capture import normal, mixed, botnet, training, Capture
from IO import Input, Output, DF
from Model import Model
from DomainLevel import Transformer
import numpy as np
import pandas as pd

/home/princio/anaconda3/envs/keras/lib/python3.8/site-packages/tldextract/.tld_set
/home/princio/anaconda3/envs/keras/lib/python3.8/site-packages/tldextract/.tld_set

In [2]:
def string_distribution(DF, string):
    df = DF.readable[DF.dn.str.find(string) >= 0]
    l = df[df['label'] == 'legit'].shape[0]
    d = df[df['label'] == 'dga'].shape[0]
    #print(f'legit={l}, dga={d}')
    return df, l, d
    #return df, df[df['label'] == 'legit'].shape[0], df[df['label'] == 'dga'].shape[0]

In [7]:
import jellyfish
def string_similarity(DF, string):
    sim = DF['dn_domain'].apply(lambda x: jellyfish.jaro_winkler(string, x))
    df = DF[sim > 0.9]
    l = df[df['label'] == 'legit'].shape[0]
    d = df[df['label'] == 'dga'].shape[0]
    #print(f'legit={l}, dga={d}')
    return df, l, d

In [62]:
captures = [normal['27']]

models = [Model.load(1), Model.load(2), Model.load(-3)]
trs= [ Transformer.NOSFX, Transformer.NOSFX_NP, Transformer.DOMAIN, Transformer.LAST ]

leveldn = {}
dga_leveldn = {}
dga_leveldn_count = {}
dga_leveldn_norm_count = {}
for capture in captures:
    for tr in trs:
        for model in models:
            input  = Input(capture, tr)
            output = Output.predict(input, model, False)
            output.threshold = 0.5
            DF = output.DF.unique().default()
            leveldn[(capture.name, tr.name, model.name)] = DF.frame().value_counts(subset=['level_dn'], sort=False, normalize=True).T.to_dict()
            DF.dga().default()
            dga_leveldn[(capture.name, tr.name, model.name)] = DF.frame()
            dga_leveldn_count[(capture.name, tr.name, model.name)] = DF.frame().value_counts(subset=['level_dn'], sort=False, normalize=False).T.to_dict()
            dga_leveldn_norm_count[(capture.name, tr.name, model.name)] = DF.frame().value_counts(subset=['level_dn'], sort=False, normalize=True).T.to_dict()

capture_leveldn_count = DF.reset().frame().value_counts(subset='level_dn', normalize=False, sort=False).to_frame()
capture_leveldn_count.loc['tot'] = capture_leveldn_count.sum(axis=0)
capture_leveldn_count = capture_leveldn_count.T
capture_leveldn_count

level_dn     1      2    >3    tot
0         1007  15636  9817  26460

## Caputre normal_31 level distribution

Necessario per capire la distribuzione dei livelli, per capire quanto sbaglia spesso ogni tipo di livello rispetto agli altri.
Ad esempio so che trova solo 8 dn per dga sbagliando per il livello-1, mentre per il livello-2 ne trova dieci volte tanto, allora devo capire se magari posso avere dieci volte tanto i ilivello-2 rispetto ai livello-1

In [42]:
dga_leveldn_count = pd.DataFrame(dga_leveldn_count).T
dga_leveldn_count['tot'] = dga_leveldn_count.sum(axis=1)
dga_leveldn_count.sort_values(by=[('tot',)], axis=0)

                                       1    2   >3  tot
normal_27 DOMAIN   OLD_LAST            3   24    5   32
                   NOSFX_1-30          1   29    6   36
                   NOSFX_NOPUNCT_1-30  1   34    8   43
          NOSFX    NOSFX_1-30          1   81   29  111
          LAST     NOSFX_1-30          1  132   15  148
                   OLD_LAST            3  135   16  154
                   NOSFX_NOPUNCT_1-30  1  155   50  206
          NOSFX    OLD_LAST            3  344  282  629
          NOSFX_NP OLD_LAST            3  344  282  629
                   NOSFX_1-30          1  342  297  640
          NOSFX    NOSFX_NOPUNCT_1-30  1  384  347  732
          NOSFX_NP NOSFX_NOPUNCT_1-30  1  384  347  732

tot indica il numero totale di dga predetti dalla nn (il top sarebbe stato tot=0)
Si può notare che il livello-1 sia parecchio minore degli altri, ma questo non sappiamo se perché effettivamente
la nn funzioni meglio con dn di livello-1 oppure perché siano in numero minore rispetto agli altri.

In [72]:
pd.options.display.float_format = '{:,.2f}'.format

df_dga_leveldn_count = pd.DataFrame(dga_leveldn_count).T
df_dga_leveldn_count['tot'] = df_dga_leveldn_count.sum(axis=1)
df_dga_leveldn_count_norm = df_dga_leveldn_count.sort_values(by=[('tot',)], axis=0).copy()
for c in df_dga_leveldn_count.columns:
    if c != ('tot',):
        df_dga_leveldn_count_norm[c[0] + '%'] = df_dga_leveldn_count[c].div(df_dga_leveldn_count[('tot',)]).mul(100)
df_dga_leveldn_count_norm

                                       1    2   >3  tot   1%    2%   >3%
normal_27 DOMAIN   OLD_LAST            3   24    5   32 9.38 75.00 15.62
                   NOSFX_1-30          1   29    6   36 2.78 80.56 16.67
                   NOSFX_NOPUNCT_1-30  1   34    8   43 2.33 79.07 18.60
          NOSFX    NOSFX_1-30          1   81   29  111 0.90 72.97 26.13
          LAST     NOSFX_1-30          1  132   15  148 0.68 89.19 10.14
                   OLD_LAST            3  135   16  154 1.95 87.66 10.39
                   NOSFX_NOPUNCT_1-30  1  155   50  206 0.49 75.24 24.27
          NOSFX    OLD_LAST            3  344  282  629 0.48 54.69 44.83
          NOSFX_NP OLD_LAST            3  344  282  629 0.48 54.69 44.83
                   NOSFX_1-30          1  342  297  640 0.16 53.44 46.41
          NOSFX    NOSFX_NOPUNCT_1-30  1  384  347  732 0.14 52.46 47.40
          NOSFX_NP NOSFX_NOPUNCT_1-30  1  384  347  732 0.14 52.46 47.40

**TL,DR;**
- La predizione su DOMAIN non dipende dal numero di subdomains.
- La predizione con NOSFX/NOSFX sbaglia il doppio con modello NOSFX.
- La predizione con NOSFX/NOSFX_NOPUNC sbaglia tangibilmente più d: la punteggiatura è utile quando si considerano più livelli.

Questa cella invece ci indica come il numero di domini errati sia sempre intorno al 0.40% rispetto al totale di ogni livello.
Infatti sebbene i domini di livello-1 predetti male fossero in numero molto minore rispetto agli altri, si può ora confermare che fosse a causa del loro esiguo numero rispetto agli altri livelli.
**Analizzando la tabella, possiamo notare come i risultati migliori siano arrivati nel caso in cui il nome di dominio venisse modificato al fine di prelevare solamente il DOMAIN**, ovvero la label subito dopo il suffisso (_ab.cd.ef.ciao.co.uk -> ciao_).
Nonostante questo, sembrerebbe comportarsi leggermente meglio la NN che considera la punteggiatura.
La NN OLD_LAST invece funziona allo stesso modo di NOSFX per i livello-1, ma per i livelli-(>1) subisce un forte peggioramento.
*Interessante* è lo 0.31% ottenuto da NOSFX/NOSFX_1-30: è comunque uno 63% in più rispetto al caso migliore (0.19%) ma è importante in quanto esso non considera solamente il livello-1 bensì tutti i livelli, riuscendo comunque a capire abbastanza bene di che tipologia si trattano.

## Quanti di quelli *sbagliati* possono trarre vantaggio dal livelli >1?

In [13]:
for ddl in dga_dn_levels:
    if ddl[1] == 'DOMAIN':
        print(ddl)
        print(dga_dn_levels[ddl].loc[dga_dn_levels[ddl]['level'] == '1'], '\n\n')

('normal_27', 'DOMAIN', 'NOSFX_1-30')
                      dn level         Y
7485  washingtonpost.com     1  0.987645


('normal_27', 'DOMAIN', 'NOSFX_NOPUNCT_1-30')
                      dn level        Y
7485  washingtonpost.com     1  0.76481


('normal_27', 'DOMAIN', 'OLD_LAST')
                        dn level         Y
523       yottlyscript.com     1  0.723575
1908   fivethirtyeight.com     1  0.974822
9340      miitbeian.gov.cn     1  0.596573
24575     yottlyscript.com     1  0.723575

Si può notare come la distribuzione

In [11]:
for ddl in dga_dn_levels:
    if ddl[1] == 'NOSFX':
        print(ddl)
        print(dga_dn_levels[ddl].loc[dga_dn_levels[ddl]['level'] == '2'].iloc[0:10], '\n\n')

('normal_27', 'NOSFX', 'NOSFX_1-30')
                                 dn level         Y
47     d6wjo2hisqfy2.cloudfront.net     2  0.869306
231    dcky6u1m8u6el.cloudfront.net     2  0.980230
680                   px.adhigh.net     2  0.611202
718   d1ibts9hn2apvm.cloudfront.net     2  0.989462
760                 ads.yieldmo.com     2  0.882147
1063  d2otzcfu7vqzws.cloudfront.net     2  0.984028
1076  d2us8jqsezvhge.cloudfront.net     2  0.549986
1085   dt3gesfwvzdvk.cloudfront.net     2  0.750309
1094  d1spgg7psata7d.cloudfront.net     2  0.841927
1467   dv4uxy777adjt.cloudfront.net     2  0.848496


('normal_27', 'NOSFX', 'NOSFX_NOPUNCT_1-30')
                               dn level         Y
0                www.msftncsi.com     2  0.998228
25            a-0001.a-msedge.net     2  0.969571
26   drcwo519tnci7.cloudfront.net     2  0.994278
47   d6wjo2hisqfy2.cloudfront.net     2  0.812799
96                  abs.twimg.com     2  0.570284
100                 pbs.twimg.com     2  0.533984
114       syndication.twitter.com     2  0.966045
187              dns.msftncsi.com     2  0.998331
231  dcky6u1m8u6el.cloudfront.net     2  0.976303
334                  tj.symcd.com     2  0.784561


('normal_27', 'NOSFX', 'OLD_LAST')
                                dn level         Y
0                 www.msftncsi.com     2  0.999620
4    d2tpbry8f62bv9.cloudfront.net     2  0.999879
26    drcwo519tnci7.cloudfront.net     2  0.999608
42                 www.mozilla.org     2  0.587084
47    d6wjo2hisqfy2.cloudfront.net     2  0.999899
92                    ss.symcd.com     2  0.654908
100                  pbs.twimg.com     2  0.568957
105            liteapps.mcafee.com     2  0.957530
187               dns.msftncsi.com     2  0.999319
231   dcky6u1m8u6el.cloudfront.net     2  0.999288

In [ ]:
from Capture import training
from IO import DF

training_DF = DF(training.dn, np.zeros(training.dn.shape[0]), np.zeros(training.dn.shape[0]))

print(training_DF.level_count_dn().to_frame().T)

training_domain = training.readable
training_domain['dn_domain'] = training_domain['dn'].apply(Transformer.domain)

In [ ]:
string_distribution(training, 'cloudfront')

In [ ]:
string_distribution(training, 'mozilla')

In [ ]:
string_distribution(training, 'goo.')

Sarebbe bello (?) cercare di trovare una correlazione tra i domini sbagliati e quelli che non lo sono rispetto al dataset di training.
Ovvero quante volte compare la stringa del d1 nel training.

In [ ]:
o = Output.predict(Input(normal['31'], Transformer.DOMAIN), Model.load(1), False)

dn = o.DF.unique().with_dn().DF.index.get_level_values(1).to_numpy()
Y = o.DF.unique().with_dn().DF['Y'].to_numpy()

df = pd.DataFrame({'dn': pd.Series(dn).apply(Transformer.domain), 'Y': Y})

df = df.drop_duplicates()

import warnings
warnings.filterwarnings('ignore')

legit = df[df['Y'] < 0.5]
legit_values=[]
c=0
for l in legit['dn']:
    c+=1
    if c % 20 == 0:
        print(c)
    _, lnum, dnum = string_similarity(training_domain, l)
    legit_values.append([l, lnum, dnum])
    
pd.DataFrame(legit_values)

In [ ]:
c=0    
dga = df[df['Y'] > 0.5]
dga_values=[]
for l in dga['dn']:
    _, lnum, dnum = string_similarity(training_domain, l)
    dga_values.append([l, lnum, dnum])
print(pd.DataFrame(dga_values).to_string())

In [ ]:
legit = df[df['Y'] < 0.5]
for l in legit['dn']:
    _, lnum, dnum = string_distribution(training, l)
    if lnum == 0:
        print('%-40s %5d  %5d' % (l, lnum, dnum))

In [ ]:
string_similarity(training, 'google')